name = "hex-row-reduce"
defaultTargets = ["HexRowReduce"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "365881fb205210e8d27c5eb011f7ddb3fe020373"

[[require]]
name = "HexMatrix"
git = "https://github.com/leanprover/hex-matrix.git"
rev = "e76a18ae921d8d8907c8ea37235a0ca5b94698cd"

[[lean_lib]]
name = "HexRowReduce"
precompileModules = true
