name = "hex-row-reduce"
defaultTargets = ["HexRowReduce"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "a3ab4fd9a79efbe6b07337836b3b5828d22d65a6"

[[require]]
name = "HexMatrix"
git = "https://github.com/leanprover/hex-matrix.git"
rev = "9b6ec9285021793e9f43e1c7b3b37da957b6f2c4"

[[lean_lib]]
name = "HexRowReduce"
precompileModules = true
